accent = "#6C0000"
cursor = "#6C0000"
foreground = "#EDEDED"
background = "#10090B"
selection_foreground = "#EDEDED"
selection_background = "#32292C"

color0 = "#120B0D"
color1 = "#6C0000"
color2 = "#6C0000"
color3 = "#6C0000"
color4 = "#6C0000"
color5 = "#6C0000"
color6 = "#6C0000"
color7 = "#EDEDED"

color8 = "#160A0D"
color9 = "#6C0000"
color10 = "#6C0000"
color11 = "#6C0000"
color12 = "#6C0000"
color13 = "#6C0000"
color14 = "#EDEDED"
color15 = "#EDEDED"
